# Generated by Django 6.1 on 2026-08-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_path',
            field=models.CharField(blank=True, help_text="Relative static path to a generated placeholder image (see products/imaging.py). Stored once so it's never regenerated on every page request.", max_length=255),
        ),
    ]
