# Generated by Django 6.1 on 2026-08-31 04:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('free_delivery_above', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('l', 'L'), ('ml', 'ml'), ('pcs', 'pcs'), ('pack', 'pack')], max_length=10)),
                ('normalized_name', models.CharField(editable=False, max_length=255)),
                ('sku', models.CharField(blank=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text="e.g. 'KA'", max_length=4)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='products.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localities', to='products.city')),
            ],
            options={
                'verbose_name_plural': 'Localities',
                'ordering': ['city__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('unknown', 'Unknown')], default='unknown', max_length=12)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_availability', to='products.locality')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='products.platform')),
            ],
            options={
                'verbose_name_plural': 'Platform availability',
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_id', models.CharField(blank=True, max_length=120)),
                ('source_url', models.URLField(blank=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('delivery_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('promotion_text', models.CharField(blank=True, max_length=120)),
                ('is_demo', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.locality')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.platform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='products.product')),
            ],
            options={
                'ordering': ['current_price'],
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('promotion_text', models.CharField(blank=True, max_length=120)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.productoffer')),
            ],
            options={
                'verbose_name_plural': 'Price histories',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='products.state'),
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.subcategory'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name'], name='idx_city_name'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('district', 'name'), name='uniq_city_per_district'),
        ),
        migrations.AddIndex(
            model_name='locality',
            index=models.Index(fields=['city', 'name'], name='idx_locality_city_name'),
        ),
        migrations.AddIndex(
            model_name='locality',
            index=models.Index(fields=['pincode'], name='idx_locality_pincode'),
        ),
        migrations.AddConstraint(
            model_name='locality',
            constraint=models.UniqueConstraint(fields=('city', 'name'), name='uniq_locality_per_city'),
        ),
        migrations.AddIndex(
            model_name='platformavailability',
            index=models.Index(fields=['locality', 'status'], name='idx_avail_locality_status'),
        ),
        migrations.AddConstraint(
            model_name='platformavailability',
            constraint=models.UniqueConstraint(fields=('platform', 'locality'), name='uniq_platform_locality'),
        ),
        migrations.AddIndex(
            model_name='productoffer',
            index=models.Index(fields=['product', 'locality'], name='idx_offer_product_locality'),
        ),
        migrations.AddIndex(
            model_name='productoffer',
            index=models.Index(fields=['platform', 'locality'], name='idx_offer_platform_locality'),
        ),
        migrations.AddIndex(
            model_name='productoffer',
            index=models.Index(fields=['is_available', 'current_price'], name='idx_offer_available_price'),
        ),
        migrations.AddConstraint(
            model_name='productoffer',
            constraint=models.UniqueConstraint(fields=('product', 'platform', 'locality'), name='uniq_offer_product_platform_locality'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['product_offer', '-recorded_at'], name='idx_history_offer_time'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='uniq_district_per_state'),
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_subcategory_per_category'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='idx_product_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='idx_product_brand'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['normalized_name'], name='idx_product_normalized_name'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory'], name='idx_product_subcategory'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('brand', 'normalized_name', 'quantity', 'unit'), name='uniq_canonical_product'),
        ),
    ]
